export const ContentErrorCode = {
  CONTENT_NOT_FOUND: "CONTENT.NOT_FOUND",
  CONTENT_INVALID_UPDATE: "CONTENT.INVALID_UPDATE",
  DAILY_LIMIT_REACHED: "CONTENT.DAILY_LIMIT_REACHED",
  EXTRACTION_FAILED: "CONTENT.EXTRACTION_FAILED",
  AI_QUOTA_EXCEEDED: "CONTENT.AI_QUOTA_EXCEEDED",
  AI_ERROR: "CONTENT.AI_ERROR",
  UNSUPPORTED_FORMAT: "CONTENT.UNSUPPORTED_FORMAT",
  FILE_TOO_LARGE: "CONTENT.FILE_TOO_LARGE",
  TIMEOUT: "CONTENT.TIMEOUT",
  DUPLICATE_URL: "CONTENT.DUPLICATE_URL",
} as const

export type ContentErrorCode =
  (typeof ContentErrorCode)[keyof typeof ContentErrorCode]
